#include "../../src/unity.h"
#include "../../extras/fixture/src/unity_fixture.h"

TEST_GROUP_RUNNER(Crypt)
{
  RUN_TEST_CASE(Crypt, TestCrypt1);
  printf("RUN_TEST_CASE=TestCrypt1");
  /*
  RUN_TEST_CASE(Crypt, TestCrypt2);
  printf("RUN_TEST_CASE=TestCrypt2");
  RUN_TEST_CASE(Crypt, TestCrypt3);
  printf("RUN_TEST_CASE=TestCrypt3");
  RUN_TEST_CASE(Crypt, TestCrypt4);
  printf("RUN_TEST_CASE=TestCrypt4");
  RUN_TEST_CASE(Crypt, TestCrypt5);
  printf("RUN_TEST_CASE=TestCrypt5");
  RUN_TEST_CASE(Crypt, TestCrypt6);
  printf("RUN_TEST_CASE=TestCrypt6");
  RUN_TEST_CASE(Crypt, TestCrypt7);
  printf("RUN_TEST_CASE=TestCrypt7");
  RUN_TEST_CASE(Crypt, TestCrypt8);
  printf("RUN_TEST_CASE=TestCrypt8");
  RUN_TEST_CASE(Crypt, TestCrypt9);
  printf("RUN_TEST_CASE=TestCrypt9");
  RUN_TEST_CASE(Crypt, TestCrypt10);
  printf("RUN_TEST_CASE=TestCrypt10");
  RUN_TEST_CASE(Crypt, TestCrypt11);
  printf("RUN_TEST_CASE=TestCrypt11");
  RUN_TEST_CASE(Crypt, TestCrypt12);
  printf("RUN_TEST_CASE=TestCrypt12");
  RUN_TEST_CASE(Crypt, TestCrypt13);
  printf("RUN_TEST_CASE=TestCrypt13");
  RUN_TEST_CASE(Crypt, TestCrypt14);
  printf("RUN_TEST_CASE=TestCrypt14");
  RUN_TEST_CASE(Crypt, TestCrypt15);
  printf("RUN_TEST_CASE=TestCrypt15");
  RUN_TEST_CASE(Crypt, TestCrypt16);
  printf("RUN_TEST_CASE=TestCrypt16");
  RUN_TEST_CASE(Crypt, TestCrypt17);
  printf("RUN_TEST_CASE=TestCrypt17");
  RUN_TEST_CASE(Crypt, TestCrypt18);
  printf("RUN_TEST_CASE=TestCrypt18");
  RUN_TEST_CASE(Crypt, TestCrypt19);
  printf("RUN_TEST_CASE=TestCrypt19");
  RUN_TEST_CASE(Crypt, TestCrypt20);
  printf("RUN_TEST_CASE=TestCrypt20");
  RUN_TEST_CASE(Crypt, TestCrypt21);
  printf("RUN_TEST_CASE=TestCrypt21");
  RUN_TEST_CASE(Crypt, TestCrypt22);
  printf("RUN_TEST_CASE=TestCrypt22");
  RUN_TEST_CASE(Crypt, TestCrypt23);
  printf("RUN_TEST_CASE=TestCrypt23");
  RUN_TEST_CASE(Crypt, TestCrypt24);
  printf("RUN_TEST_CASE=TestCrypt24");
  RUN_TEST_CASE(Crypt, TestCrypt25);
  printf("RUN_TEST_CASE=TestCrypt25");
  RUN_TEST_CASE(Crypt, TestCrypt26);
  printf("RUN_TEST_CASE=TestCrypt26");
  RUN_TEST_CASE(Crypt, TestCrypt27);
  printf("RUN_TEST_CASE=TestCrypt27");
  RUN_TEST_CASE(Crypt, TestCrypt28);
  printf("RUN_TEST_CASE=TestCrypt28");
  RUN_TEST_CASE(Crypt, TestCrypt29);
  printf("RUN_TEST_CASE=TestCrypt29");
  RUN_TEST_CASE(Crypt, TestCrypt30);
  printf("RUN_TEST_CASE=TestCrypt30");
  RUN_TEST_CASE(Crypt, TestCrypt31);
  printf("RUN_TEST_CASE=TestCrypt31");
  RUN_TEST_CASE(Crypt, TestCrypt32);
  printf("RUN_TEST_CASE=TestCrypt32");
  RUN_TEST_CASE(Crypt, TestCrypt33);
  printf("RUN_TEST_CASE=TestCrypt33");
  RUN_TEST_CASE(Crypt, TestCrypt34);
  printf("RUN_TEST_CASE=TestCrypt34");
  RUN_TEST_CASE(Crypt, TestCrypt35);
  printf("RUN_TEST_CASE=TestCrypt35");
  RUN_TEST_CASE(Crypt, TestCrypt36);
  printf("RUN_TEST_CASE=TestCrypt36");
  RUN_TEST_CASE(Crypt, TestCrypt37);
  printf("RUN_TEST_CASE=TestCrypt37");
  RUN_TEST_CASE(Crypt, TestCrypt38);
  printf("RUN_TEST_CASE=TestCrypt38");
  RUN_TEST_CASE(Crypt, TestCrypt39);
  printf("RUN_TEST_CASE=TestCrypt39");
  RUN_TEST_CASE(Crypt, TestCrypt40);
  printf("RUN_TEST_CASE=TestCrypt40");
  RUN_TEST_CASE(Crypt, TestCrypt41);
  printf("RUN_TEST_CASE=TestCrypt41");
  RUN_TEST_CASE(Crypt, TestCrypt42);
  printf("RUN_TEST_CASE=TestCrypt42");
  RUN_TEST_CASE(Crypt, TestCrypt43);
  printf("RUN_TEST_CASE=TestCrypt43");
  RUN_TEST_CASE(Crypt, TestCrypt44);
  printf("RUN_TEST_CASE=TestCrypt44");
  RUN_TEST_CASE(Crypt, TestCrypt45);
  printf("RUN_TEST_CASE=TestCrypt45");
  RUN_TEST_CASE(Crypt, TestCrypt46);
  printf("RUN_TEST_CASE=TestCrypt46");
  RUN_TEST_CASE(Crypt, TestCrypt47);
  printf("RUN_TEST_CASE=TestCrypt47");
  RUN_TEST_CASE(Crypt, TestCrypt48);
  printf("RUN_TEST_CASE=TestCrypt48");
  */
}