#include "../../src/unity.h"
#include "../../extras/fixture/src/unity_fixture.h"

TEST_GROUP_RUNNER(Crypt)
{
  RUN_TEST_CASE(Crypt, TestCrypt1);
  RUN_TEST_CASE(Crypt, TestCrypt2);
  RUN_TEST_CASE(Crypt, TestCrypt3);
  RUN_TEST_CASE(Crypt, TestCrypt4);
  RUN_TEST_CASE(Crypt, TestCrypt5);
  RUN_TEST_CASE(Crypt, TestCrypt6);
  RUN_TEST_CASE(Crypt, TestCrypt7);
  RUN_TEST_CASE(Crypt, TestCrypt8);
  RUN_TEST_CASE(Crypt, TestCrypt9);
  RUN_TEST_CASE(Crypt, TestCrypt10);
  RUN_TEST_CASE(Crypt, TestCrypt11);
  RUN_TEST_CASE(Crypt, TestCrypt12);
  RUN_TEST_CASE(Crypt, TestCrypt13);
  RUN_TEST_CASE(Crypt, TestCrypt14);
  RUN_TEST_CASE(Crypt, TestCrypt15);
  RUN_TEST_CASE(Crypt, TestCrypt16);
  RUN_TEST_CASE(Crypt, TestCrypt17);
  RUN_TEST_CASE(Crypt, TestCrypt18);
  RUN_TEST_CASE(Crypt, TestCrypt19);
  RUN_TEST_CASE(Crypt, TestCrypt20);
  RUN_TEST_CASE(Crypt, TestCrypt21);
  RUN_TEST_CASE(Crypt, TestCrypt22);
  RUN_TEST_CASE(Crypt, TestCrypt23);
  RUN_TEST_CASE(Crypt, TestCrypt24);
  RUN_TEST_CASE(Crypt, TestCrypt25);
  RUN_TEST_CASE(Crypt, TestCrypt26);
  RUN_TEST_CASE(Crypt, TestCrypt27);
  RUN_TEST_CASE(Crypt, TestCrypt28);
  RUN_TEST_CASE(Crypt, TestCrypt29);
  RUN_TEST_CASE(Crypt, TestCrypt30);
  RUN_TEST_CASE(Crypt, TestCrypt31);
  RUN_TEST_CASE(Crypt, TestCrypt32);
  RUN_TEST_CASE(Crypt, TestCrypt33);
  RUN_TEST_CASE(Crypt, TestCrypt34);
  RUN_TEST_CASE(Crypt, TestCrypt35);
  RUN_TEST_CASE(Crypt, TestCrypt36);
  RUN_TEST_CASE(Crypt, TestCrypt37);
  RUN_TEST_CASE(Crypt, TestCrypt38);
  RUN_TEST_CASE(Crypt, TestCrypt39);
  RUN_TEST_CASE(Crypt, TestCrypt40);
  RUN_TEST_CASE(Crypt, TestCrypt41);
  RUN_TEST_CASE(Crypt, TestCrypt42);
  RUN_TEST_CASE(Crypt, TestCrypt43);
  RUN_TEST_CASE(Crypt, TestCrypt44);
  RUN_TEST_CASE(Crypt, TestCrypt45);
  RUN_TEST_CASE(Crypt, TestCrypt46);
  RUN_TEST_CASE(Crypt, TestCrypt47);
  RUN_TEST_CASE(Crypt, TestCrypt48);
}